config/routes.rb
CoachMe::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => 'sessions'}
  
  resources :users do
    resources :trainings do
      resources :exercises
    end
  end
  
  resources :trainings do
    resources :exercises
  end
  
  resources :exercises

  resources :relationships
  
  root :to => 'home#index'
end

app/models/training.rb
class Training < ActiveRecord::Base
  has_many :exercises, :order => "id ASC"
  belongs_to :user
  attr_accessible :started_at, :title, :feeling, :temperature, :weather, :surface, :notes

  FEELING = [["Awesome", "awesome"],["Good", "good"],["So-so", "soso"],["Sluggish", "sluggish"],["Injured", "injured"]]
  FEELING_VALUES =  {"awesome" => 5, "good" => 4, "soso" => 3, "sluggish" => 2, "injured" => 1}

  TEMPERATURE = [["Hot", "hot"],["Warm", "warm"],["Mild", "mild"],["Cold", "cold"],["Freezing", "freezing"]]

  WEATHER = [["Normal", "normal"], ["Rainy", "rainy"],["Cloudy", "cloudy"],["Sunny", "sunny"],["Snowy", "snowy"], ["Windy", "windy"]]

  SURFACE = [["Running track", "track"], ["Road", "road"],["Offroad", "offroad"],["Mixed", "mixed"],["Beach", "beach"], ["Hills", "hills"]]
  
  def total_distance
    exercises.map(&:distance).map(&:to_f).sum
  end

  # if it has notes or at least one exercise
  def needs_summary?
    notes.present? || exercises.present?
  end

  def feeling_value
    FEELING_VALUES[feeling] || 0
  end

  def description_of(field)
    val = send(field.to_sym)
    return "-" if val.blank?
    values = self.class.const_get(field.to_s.upcase.to_sym)
    values.detect {|x| x.last == val}.first
  end

  def title
     read_attribute(:title).blank? ? "Untitled training" :  read_attribute(:title)
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  skip_authorization_check
  skip_before_filter :authenticate_user!, :only => [:index, :show]
  before_filter :initialize_athlete
  before_filter :authorize_read, :only => [:index, :show]
  before_filter :authorize_manage, :except => [:index, :show]
  respond_to :html, :json
  
  include TrainingsHelper
  # GET /trainings
  # GET /trainings.json
  def index
    authorize! :read_trainings, @athlete
    @user = @athlete

    @trainings = Training.where("started_at > ? and user_id = ?", Date.today - 1.year, @user.id).includes(:exercises)
    @training_groups = group_trainings_for_index_page(@trainings, Date.today)
    
    respond_with @trainings
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
    @training = Training.find(params[:id])
    
    authorize! :read_trainings, @training.user
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @training }
    end
  end

  # GET /trainings/new
  # GET /trainings/new.json
  def new
    @training = Training.new
    @training.user = @athlete
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @training }
    end
  end

  # GET /trainings/1/edit
  def edit
    authorize! :manage_trainings, @athlete
    @training = Training.find(params[:id])
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = Training.new(params[:training])
    @training.user = @athlete

    @training.title = 'Untitled'
    @training.started_at = Date.today
    
    respond_to do |format|
      if @training.save
        format.html { redirect_to "#{training_path(@training)}/#/edit", notice: 'Training was successfully created.' }
        format.json { render json: @training, status: :created, location: @training }
      else
        format.html { render action: "new" }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trainings/1
  # PUT /trainings/1.json
  def update
    @training = Training.find(params[:id])
    respond_to do |format|
      if @training.update_attributes(params[:training])
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training = Training.find(params[:id])
    @training.destroy

    respond_to do |format|
      format.html { redirect_to trainings_url }
      format.json { head :no_content }
    end
  end

  private

  def initialize_athlete
    @athlete = if params[:user_id]
                User.find(params[:user_id])
               elsif current_user.present?
                 current_user
               else
                 redirect_to new_user_session_url
               end
  end

  def authorize_manage
    authorize! :manage_trainings, @athlete
  end

  def authorize_read
    authorize! :read_trainings, @athlete
  end
end

app/helpers/trainings_helper.rb
module TrainingsHelper

  def group_trainings_for_index_page(trainings, today)
    groups = []
    return groups if trainings.blank?
    tc = trainings.count
    st = trainings.sort_by {|t| t.started_at}.reverse # sorted trainings
    oldest = st.last.started_at
    newest = st.first.started_at

    # weeks represented by their end
    week = newest.end_of_week
    ptr = 0 # pointing the next trainings to be grouped
    
    while oldest < week do
      prev_week = week - 1.week
      w = OpenStruct.new
      w.week = week.dup
      w.trainings = []
      w.by_day = {}
      groups << w

      while ptr < tc && prev_week < st[ptr].started_at && st[ptr].started_at <= week do
        t = st[ptr]
        w.trainings << t
        (w.by_day[t.started_at.to_date] ||= []) << t
        ptr += 1
      end

      w.future = week.beginning_of_week > today
      w.past = week.end_of_week < today
      w.current = week.beginning_of_week <= today && week.end_of_week >= today
      
      week = week - 1.week
    end

    groups
  end
end

app/views/trainings/_form.html.erb
<%= form_for([@athlete, @training]) do |f| %>
  <% if @training.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@training.errors.count, "error") %> prohibited this training from being saved:</h2>

      <ul>
      <% @training.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <h1><%= controller.action_name.capitalize %> Training</h1>
  <hr/>
  <fieldset>
    
    <div class="row">
      <div class="control-group span7">
        <%= f.label :title, 'What did you do?', :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :title, :class => 'text_field span7', :placeholder => 'Short description of the activity' %>
        </div>
      </div>

      <div class="control-group span2 pull-right">
        <%= f.label :started_at, 'When did it happen?', :class => 'control-label' %>
        <div class="controls">
          <div class="input-append">
            <%= f.text_field :started_at, :value => l(@training.started_at || Time.now, :format => :day), :class => 'datepicker input-small' %>
            <span class="add-on"><i class="icon-calendar"></i></span>
          </div>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="span3">
        <div class="control-group">
          <%= f.label :feeling, 'Feeling', :class => 'control-label' %>
          <div class="controls">
            <%= f.select :feeling, Training::FEELINGS, {:include_blank => '-- choose one --'} %>
          </div>
        </div>
    
        <div class="control-group">
          <%= f.label :temperature, 'Temperature', :class => 'control-label' %>
          <div class="controls">
            <%= f.select :temperature, [["Hot", "hot"],["Warm", "warm"],["Mild", "mild"],["Cold", "cold"],["Freezing", "freezing"]], {:include_blank => '-- choose one --'} %>
          </div>
        </div>
    
        <div class="control-group">
          <%= f.label :weather, 'Weather', :class => 'control-label' %>
          <div class="controls">
            <%= f.select :weather, [["Normal", "normal"], ["Rainy", "rainy"],["Cloudy", "cloudy"],["Sunny", "sunny"],["Snowy", "snowy"]], {:include_blank => '-- choose one --'} %>
          </div>
        </div>
    
        <div class="control-group">
          <%= f.label :surface, 'Surface', :class => 'control-label' %>
          <div class="controls">
            <%= f.select :surface, [["Road", "road"],["Trial", "trial"],["Offroad", "offroad"],["Mixed", "mixed"],["Beach", "beach"]], {:include_blank => '-- choose one --'} %>
          </div>
        </div>
      </div>
    
      <div class="control-group span9">
        <%= f.label :notes, 'Notes', :class => 'control-label' %>
        <div class="controls">
          <%= f.text_area :notes, :class => 'span6', :rows => 12 %>
        </div>
      </div>
    </div>
    
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', trainings_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/trainings/_future_summary.html.haml
- if (trainings = @training_groups.take_while {|w| w.future || w.current}).present?
  %h3 Planned trainings:
  %br

  %table{:class=>'table future-summary-table'}
    - trainings.each_with_index do |week, idx|
      %tr
        - monday = week.week.beginning_of_week
        - for day in ((0..6).map {|n| monday + n.days})
          %td.calendar-day{:class => ("today" if day == Date.today)}
            - if day >= Date.today
              %div.clearfix
                - if day == Date.today
                  %span.name-of-day
                    Today
                - elsif idx == 0
                  %span.name-of-day
                    = day.strftime('%A')
                %span.day-of-month
                  = day.strftime('%d')
              - trainings_on_this_day = week.by_day[day.to_date] || []
              - trainings_on_this_day.each_with_index do |training, idx2|
                - if training.needs_summary?
                  = link_to training.title, user_training_path(@athlete, training), { :rel=> "popover", :'data-trigger' => "hover", :'data-placement'=> "bottom", :'data-delay'=>"300", :'data-title'=>"Summary", :'data-content'=>"#{render(:partial => 'training_summary', :locals => {:training => training})}"}
                  %i{:class=>'icon-comment'}
                - else
                  = link_to training.title, user_training_path(@athlete, training)
                - if idx2 < trainings_on_this_day.count - 1
                  %hr

app/views/trainings/_past_training_list.html.erb
<% if (completed_trainings = @training_groups.reject {|x| x.future
   }).present? %>

<h3>Completed trainings:</h3>
<br/>
<% for group in @training_groups.reject {|x| x.future } %>

  <div class="training-week" style="margin-bottom: 20px; <%= 'background-color:
                                    lightyellow; border: 1px dashed
                                    gray' if group.current %>">
  <% if group.current %>
    <h3 style="padding: 10px 0 0 10px; text-decoration: underline">Current week</h3>
  <% end %>
  <h4 style="padding: 10px">
    <%= "#{group.week.strftime('Weeek #%W')}"%>
    <span style="color:gray; font-size: 12px; font-weight:
                 normal">
      <%= "(#{l(group.week.beginning_of_week, :format => :month_and_day)} -
           #{l(group.week.end_of_week, :format => :month_and_day)})"  %>
    </span>

  </h4>

  <% if group.trainings.empty? %>
    <table class='table'>
      <tr>
        <td>No stored trainings for this week.</td>
      </tr>
    </table>
  <% end %>


  <% unless group.trainings.empty? %>
    
    <table class="table" sytle="mrgin-bottom: 0">
      <tbody>
        <% for training in group.trainings %>
          <% if training.started_at <= Date.today %>
          <% if training.needs_summary? %>
            <tr rel="popover" 
                data-trigger="hover"
                data-placement="bottom"
                data-delay="300"
                data-title="Summary"
                data-content="<%= 
                            render(:partial => 'training_summary',
                                   :locals => {:training => training})%>">
          <% else %>
            <tr>
          <% end %>
            <td style="width: 20%; padding-left: 20px">
              <span class="label label-info" style="padding-right: 1px;margin-right: 5px">
                <%= " #{training.started_at.strftime("%b %d")}" %>
              </span>
              <%= "#{training.started_at.strftime("%A")}" %>
            </td>
            <td style="width: 20%">
              <% for i in 1..training.feeling_value %>
                <i class="icon-star" style="color: orange"></i>
              <% end %>
              <% for i in 1..(5-training.feeling_value) %>
                <i class="icon-star-empty" style="color: lightgray"></i>
              <% end %>              
            </td>
            <td  style="width: 50%">
              <%= link_to training.title, user_training_path(@athlete,training) %>
              <% if training.needs_summary? %>
                <i class="icon-comment"></i>
              <% end %>
            </td>
            <td></td>
            <td  style="width: 10%"><%= "#{training.total_distance} km" %></td>
          </tr>
      
        <% end %>
        <% end %>
      <tr>
        <th></th>
        <th></th>
        <th></th>
        <th style="text-align:right">Total</th>
        <th><%= "%5.2f km" % group.trainings.map(&:total_distance).sum %></th>
      </tr>
      </tbody>
    </table>
  <% end %>

  </div>
<% end %>
<% end %>

app/views/trainings/_relations.html.haml
.row
  .span6
    - if (athletes = current_user.trainees).present?
      %h3 My Athletes
      - for athlete in athletes
        = link_to athlete.full_name, user_trainings_path(athlete)
    - if (coaches = current_user.trainers).present?    
      %h3 My coaches
      - for coach in coaches
        = link_to coach.full_name, user_path(coach)
  .span6
    - if (following = current_user.viewed_athletes).present?
      %h3 Athletes I'm following
      - for athlete in following
        = link_to athlete.full_name, user_trainings_path(athlete)
    - if (followers = current_user.viewers).present?
      %h3 My Followers
      - for athlete in followers
        = link_to athlete.full_name, user_trainings_path(athlete)

app/views/trainings/_training_summary.html.erb
<% if training.notes.present? %>
  <p><%= training.notes %></p>
  <br/>
<% end %>

<table style='width: 100%'>
  <% training.exercises.each do |exercise| %>
    <tr data-exercise-id='<%= exercise.id %>'>
      <td class='exercise-name'><%= exercise.name %></td>
      <td class='exercise-distance'><%= "#{exercise.distance} km" %></td>
      <td class='exercise-time'><%= exercise.formatted_time %></td>
    </tr>
  <% end %>
</table>

app/views/trainings/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @training %> |
<%= link_to 'Back', trainings_path %>

app/views/trainings/index.html.erb
<%= render :partial => 'relations' %>

<h1>Trainings</h1><br/>

<%= render :partial => 'future_summary' %>

<% for group in @training_groups.reject {|x| x.future } %>

  <div class="training-week" style="margin-bottom: 20px; <%= 'background-color:
                                    lightyellow; border: 1px dashed
                                    gray' if group.current %>">
  <% if group.current %>
    <h3 style="padding: 10px 0 0 10px; text-decoration: underline">Current week</h3>
  <% end %>
  <h4 style="padding: 10px">
    <%= "#{group.week.strftime('Weeek #%W')}"%>
    <span style="color:gray; font-size: 12px; font-weight:
                 normal">
      <%= "(#{l(group.week.beginning_of_week, :format => :month_and_day)} -
           #{l(group.week.end_of_week, :format => :month_and_day)})"  %>
    </span>

  </h4>

  <% if group.trainings.empty? %>
    <table class='table'>
      <tr>
        <td>No stored trainings for this week.</td>
      </tr>
    </table>
  <% end %>


  <% unless group.trainings.empty? %>
    
    <table class="table" sytle="mrgin-bottom: 0">
      <tbody>
        <% for training in group.trainings %>
          <% if training.started_at <= Date.today %>
          <% if training.needs_summary? %>
            <tr rel="popover" 
                data-trigger="hover"
                data-placement="bottom"
                data-delay="300"
                data-title="Summary"
                data-content="<%= 
                            render(:partial => 'training_summary',
                                   :locals => {:training => training})%>">
          <% else %>
            <tr>
          <% end %>
            <td class="span2">
              <span class="label label-info" style="padding-right: 1px;margin-right: 5px">
                <%= " #{training.started_at.strftime("%b %d")}" %>
              </span>
              <%= "#{training.started_at.strftime("%A")}" %>
            </td>
            <td class="span4">
              <%= link_to training.title, training_path(training) %>
              <% if training.needs_summary? %>
                <i class="icon-comment"></i>
              <% end %>
            </td>
            <td class="span2"><%= "#{training.total_distance} km" %></td>
          </tr>
      
        <% end %>
        <% end %>
      <tr>
        <th></th>
        <th style="text-align:right">Total</th>
        <th><%= "%5.2f km" % group.trainings.map(&:total_distance).sum %></th>
      </tr>
      </tbody>
    </table>
  <% end %>

  </div>
<% end %>

app/views/trainings/index.html.haml
- if myself? @user
  %hr
  = render :partial => 'relations'
  %hr

.row
  .span8
    - if myself? @user
      %h1 My Trainings
    - else
      %h1
        Trainings of 
        #{link_to @user.full_name, user_path(@user)}
  .span4
    - if can? :manage_trainings, @user
      .pull-right{style: 'padding-top: 10px'}
        = form_for([@user, Training.new]) do |f|
          %button.btn.btn-primary
            - if myself? @user
              Create new training for myself
            - else
              = "Create new training for #{@user.first_name}"
            .i.icon-arrow-right
%br


%br
= render :partial => 'future_summary'

%br
= render :partial => 'past_training_list'

app/views/trainings/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', trainings_path %>

app/views/trainings/show.html.haml
#training-show-page{:'data-training-id' => @training.id}
  .button-bar.clearfix
    .pull-left{ style: 'margin-right: 10px'}
      = link_to user_trainings_path(@training.user), :class => 'btn'  do
        .i.icon-arrow-left
        Back to the trainings

    - if can? :manage_trainings, @training.user
      .btn-group.pull-left
        -# = link_to edit_training_path(@training), :class => 'btn btn-info' do
        -#   .i.icon-check
        -#   Mark as complete
        = link_to '#', :class => 'btn edit-button' do
          .i.icon-edit
          Edit
        = link_to training_path(@training), :class => 'btn', :method => :delete, :confirm => 'Are you sure?'  do
          .i.icon-trash
          Delete

  %hr

  .row
    .span8
      .training-title
        %h2= @training.title
    .span2
      .pull-right
        %h3
          %i.icon-calendar
          %span.training-date
            -if @training.started_at.present?
              =l @training.started_at, :format => :day
  %hr


  .row
    .span8
      %h4 Notes
      %br
        .training-notes
          .well
            = @training.notes

    .span4
      %br
      %br
      %table.table.table-bordered.features-table
        %tr
          %th Feeling
          %td.training-feeling
            %span
              = @training.description_of(:feeling)
        %tr
          %th Temperature
          %td.training-temperature
            %span
              = @training.description_of(:temperature)
        %tr
          %th Weather
          %td.training-weather
            %span
              = @training.description_of(:weather)
        %tr
          %th Surface
          %td.training-surface
            %span
              = @training.description_of(:surface)

%hr
%h3 Exercises for this training:

%table.table.table-striped.exercise-table{:'data-training-id' => @training.id}
  %thead
    %tr
      %th{:width => '30%'} 
        Description
      %th{:width => '30%'} 
        Distance
      %th{:width => '30%'} 
        Time
      %th{:width => '3%'}      
  %tbody
    - @training.exercises.each do |exercise|
      %tr{:'data-exercise-id' => exercise.id}
        %td.field.exercise-name= exercise.name
        %td.field.exercise-distance= exercise.distance
        %td.field.exercise-time= exercise.formatted_time
        %td.delete-exercise
          - if can? :manage_trainings, @training.user
            %button.btn.btn-mini
              %i.icon-trash
              
%script
  feelingValues = [];
  - for v in Training::FEELING
    ="feelingValues.push({label: '#{v.first}', value: '#{v.last}'});"
  temperatureValues = [];
  - for v in Training::TEMPERATURE
    ="temperatureValues.push({label: '#{v.first}', value: '#{v.last}'});"
  weatherValues = [];
  - for v in Training::WEATHER
    ="weatherValues.push({label: '#{v.first}', value: '#{v.last}'});"
  surfaceValues = [];
  - for v in Training::SURFACE
    ="surfaceValues.push({label: '#{v.first}', value: '#{v.last}'});"

- if can? :manage_trainings, @training.user  
  %hr
  %h3 Add new exercise:
  %br

  %table{:width => '100%'}
    %tr.exercise-form-row
      %td{:width => '30%'}
        = text_field "exercise", "name", placeholder: 'Exercise description'
      %td{:width => '30%'}
        = text_field "exercise", "distance", placeholder: 'Distance (km)'
      %td{:width => '30%'}
        Time:
        = select("exercise", "hours", (0..5).map {|p| [ p, p ] }, {}, {:style => 'width: 55px'})
        h
        = select("exercise", "minutes", (0..59).map {|p| [ ("%02d" % p), p ] }, {}, {:style => 'width: 55px'})
        m
        = select("exercise", "seconds", (0..59).map {|p| [ ("%02d" % p), p ] }, {}, {:style => 'width: 55px'})
        s
      %td{:width => '10%'}
        %button.btn.btn-primary.pull-right          
          Add
          .i.icon-plus