config/routes.rb
CoachMe::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => 'sessions'}
  
  resources :users do
    resources :trainings do
      resources :exercises
    end
  end
  
  resources :trainings do
    resources :exercises
  end
  
  resources :exercises

  resources :relationships
  
  root :to => 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :public
  # attr_accessible :title, :body
  
  has_many :trainings

  has_many :trainer_associations, :class_name => 'Relationship', :foreign_key => 'subject_id', :conditions => "rel = 'TRAINER_OF'"
  has_many :trainers, :through => :trainer_associations, :source => :object

  has_many :trainees_associations, :class_name => 'Relationship', :foreign_key => 'object_id', :conditions => "rel = 'TRAINER_OF'"
  has_many :trainees, :through => :trainees_associations, :source => :subject

  has_many :viewer_associations, :class_name => 'Relationship', :foreign_key => 'subject_id', :conditions => "rel = 'VIEWER_OF'"
  has_many :viewers, :through => :viewer_associations, :source => :object

  has_many :viewed_athlete_associations, :class_name => 'Relationship', :foreign_key => 'object_id', :conditions => "rel = 'VIEWER_OF'"
  has_many :viewed_athletes, :through => :viewed_athlete_associations, :source => :subject
  validates_presence_of :first_name
  validates_presence_of :last_name

  
  def admin?
    role == "ADMIN"
  end

  def trainer_of?(subject)
    self.trainees.include? subject
  end

  def trained_by?(subject)
    self.trainers.include? subject
  end
  
  def viewer_of?(subject)
    self.viewed_athletes.include? subject
  end

  def viewed_by?(subject)
    self.viewers.include? subject
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  respond_to :html, :json
  
  def index
    authorize! :manage, :users
    @users = User.order("id desc").all
  end

  def show
    @user = User.find(params[:id])
    authorize! :read, @user
    
    respond_with(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.haml
%h1 Users
%table.table.table-striped
  %thead
    %tr
      %th ID
      %th Email
      %th Current sign in at
      %th Sign in count
  %tbody
    - @users.each do |user|
      %tr
        %td=user.id
        %td=link_to user.email, user_trainings_path(user)
        %td=l user.current_sign_in_at, :format => :day_and_time
        %td=user.sign_in_count
%h1 Relations

%table.table
  %tr
    %th Object
    %th Relation
    %th Subject
    %th
  - for rel in Relationship.all
    %tr
      %td=rel.object.email
      %td=rel.rel
      %td=rel.subject.email
      %td
        =link_to relationship_path(rel), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini' do
          %i.icon-trash

= form_for Relationship.new do |f|
  %strong Create new relation:
  = f.select :object_id, User.all.collect {|p| [ p.email, p.id ] }, { :include_blank => true }
  = f.select :rel, Relationship::CODES, { :include_blank => true }
  = f.select :subject_id, User.all.collect {|p| [ p.email, p.id ] }, { :include_blank => true }
  = f.submit "Create relation", :class => "btn, btn-primary"

app/views/users/show.html.haml
%h1="The profile of #{@user.full_name}"

%p
  Send an email to
  =mail_to @user.email, @user.full_name
  if you want.