config/routes.rb
CoachMe::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => 'sessions'}
  
  resources :users do
    resources :trainings do
      resources :exercises
    end
  end
  
  resources :trainings do
    resources :exercises
  end
  
  resources :exercises

  resources :relationships
  
  root :to => 'home#index'
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  respond_to :html, :json
  # POST /exercises
  # POST /exercises.json
  def create
    @training = Training.find(params[:exercise].delete(:training_id))
    @exercise = @training.exercises.build(params[:exercise])
    authorize! :manage_trainings, @training.user
    @exercise.save
    respond_with(@exercise)
  end

  # PUT /exercises/1
  # PUT /exercises/1.json
  def update
    params[:exercise].delete(:training_id)
    @exercise = Exercise.find(params[:id])
    authorize! :manage_trainings, @exercise.training.user
    if @exercise.update_attributes(params[:exercise])
      render text: "", status: 200
    else
      render text: "", status: 500
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise = Exercise.find(params[:id])
    authorize! :manage_trainings, @exercise.training.user
    @exercise.destroy

    respond_to do |format|
      format.html { redirect_to training_url(@training) }
      format.json { head :no_content }
    end
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.erb
<%= form_for([@training, @training.excercises.build]) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :distance %><br />
    <%= f.text_field :distance %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.number_field :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing exercise</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<h1>Listing exercises</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Position</th>
    <th>Distance</th>
    <th>Time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exercises.each do |exercise| %>
  <tr>
    <td><%= exercise.name %></td>
    <td><%= exercise.position %></td>
    <td><%= exercise.distance %></td>
    <td><%= exercise.time %></td>
    <td><%= link_to 'Show', exercise %></td>
    <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
    <td><%= link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Exercise', new_exercise_path %>

app/views/exercises/new.html.erb
<h1>New exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @exercise.name %>
</p>

<p>
  <b>Position:</b>
  <%= @exercise.position %>
</p>

<p>
  <b>Distance:</b>
  <%= @exercise.distance %>
</p>

<p>
  <b>Time:</b>
  <%= @exercise.time %>
</p>


<%= link_to 'Edit', edit_exercise_path(@exercise) %> |
<%= link_to 'Back', exercises_path %>